name: deploying using cicd
on:
    push:
        branches: [master]
    
jobs:
    ssh_server:
        runs-on: ubuntu-latest
        name: deploy the app to the node
        steps: 
            - run: |
                echo "${{secrets.SSH_KEY}}" > ~/asim.pem
                chmod 700 ~/asim.pem
                ssh -o StrictHostKeyChecking=no -i ~/asim.pem ubuntu@15.206.88.153 -t "cd sum-server && git pull origin master && pm2 restart index"





    

