name: deploying using cicd
on:
    push:
        branches: [master]
    
jobs:
    ssh_server:
        runs-on: ubuntu-latest
        name: deploy the app to the node
        steps: 
            - run: |
                echo "${{secrets.SSH_KEY}}" > ~/asim.pem
                chmod 700 ~/asim.pem
                ssh -i ~/asim.pem ubuntu@15.206.88.153 \
                "export NVM_DIR=\$HOME/.nvm && source \$NVM_DIR/nvm.sh && nvm use 22 && which npm"






    

