name: deploying using cicd
on:
    push:
        branches: [master]
    
jobs:
    ssh_server:
        runs-on: ubuntu-latest
        name: deploy the app to the node
        steps: 
            - run: |
                echo "${{secrets.SSH_KEY}}" > ~/asim.pem
                chmod 700 ~/asim.pem
                ssh -o StrictHostKeyChecking=no -i ~/asim.pem ubuntu@15.206.88.153 \
                "cd sum-server && git pull origin master && export PATH=/home/ubuntu/.nvm/versions/node/v22.15.0/bin:\$PATH && npm install && pm2 restart index"






    

