name: deploying using cicd
on:
    push:
        branches: [master]
    
jobs:
    ssh_server:
        runs-on: ubuntu-latest
        name: deploy the app to the node
        steps: 
            - run: |
                echo "${{secrets.SSH_KEY}}" > ~/asim.pem
                chmod 700 ~/asim.pem
                ssh -o StrictHostKeyChecking=no -i ~/asim.pem ubuntu@15.206.88.153 -t "cd sum-server && git pull --no-rebase origin master && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install && pm2 restart index"





    

