name: deploying using cicd
on:
    push:
        branches: [main]
    
jobs:
    ssh_server:
        runs-on: ubuntu-latest
        name: deploy the app to the node
        steps: 
            - run: |
                echo "{{secrets.SSH_KEY}}" &> ~/ssh_key
                chmod 700 ~/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.88.153 -t "cd sum-server && git pull origin main && pm2 restart index"





    

